/// <reference path="../../../globals.d.ts"/>

declare module 'goog:goog.events.PointerFallbackEventType' {
    import alias = goog.events.PointerFallbackEventType;
    export default alias;
}

declare module 'goog:goog.events.EventType' {
    import alias = goog.events.EventType;
    export default alias;
}

declare namespace goog.events {
    /**
     * Constants for event names.
     * @enum {string}
     */
    enum EventType {
        ABORT = 'abort',
        ACTIVATE = 'activate',
        AFTERPRINT = 'afterprint',
        ANIMATIONEND = '',
        ANIMATIONITERATION = '',
        ANIMATIONSTART = '',
        APPINSTALLED = 'appinstalled',
        BEFORECOPY = 'beforecopy',
        BEFORECUT = 'beforecut',
        BEFOREINPUT = 'beforeinput',
        BEFOREINSTALLPROMPT = 'beforeinstallprompt',
        BEFOREPASTE = 'beforepaste',
        BEFOREPRINT = 'beforeprint',
        BEFOREUNLOAD = 'beforeunload',
        BLUR = 'blur',
        CANPLAY = 'canplay',
        CANPLAYTHROUGH = 'canplaythrough',
        CHANGE = 'change',
        CLICK = 'click',
        COMPOSITIONEND = 'compositionend',
        COMPOSITIONSTART = 'compositionstart',
        COMPOSITIONUPDATE = 'compositionupdate',
        CONNECT = 'connect',
        CONSOLEMESSAGE = 'consolemessage',
        CONTEXTMENU = 'contextmenu',
        CONTROLLERCHANGE = 'controllerchange',
        COPY = 'copy',
        CUT = 'cut',
        DBLCLICK = 'dblclick',
        DEACTIVATE = 'deactivate',
        DEVICECHANGE = 'devicechange',
        DEVICEMOTION = 'devicemotion',
        DEVICEORIENTATION = 'deviceorientation',
        DOMATTRMODIFIED = 'DOMAttrModified',
        DOMCHARACTERDATAMODIFIED = 'DOMCharacterDataModified',
        DOMCONTENTLOADED = 'DOMContentLoaded',
        DOMNODEINSERTED = 'DOMNodeInserted',
        DOMNODEINSERTEDINTODOCUMENT = 'DOMNodeInsertedIntoDocument',
        DOMNODEREMOVED = 'DOMNodeRemoved',
        DOMNODEREMOVEDFROMDOCUMENT = 'DOMNodeRemovedFromDocument',
        DOMSUBTREEMODIFIED = 'DOMSubtreeModified',
        DRAG = 'drag',
        DRAGEND = 'dragend',
        DRAGENTER = 'dragenter',
        DRAGLEAVE = 'dragleave',
        DRAGOVER = 'dragover',
        DRAGSTART = 'dragstart',
        DROP = 'drop',
        DURATIONCHANGE = 'durationchange',
        EMPTIED = 'emptied',
        ENDED = 'ended',
        ERROR = 'error',
        EXIT = 'exit',
        FETCH = 'fetch',
        FOCUS = 'focus',
        FOCUSIN = 'focusin',
        FOCUSOUT = 'focusout',
        FOREIGNFETCH = 'foreignfetch',
        GOTPOINTERCAPTURE = 'gotpointercapture',
        HASHCHANGE = 'hashchange',
        HELP = 'help',
        INPUT = 'input',
        INSTALL = 'install',
        KEYDOWN = 'keydown',
        KEYPRESS = 'keypress',
        KEYUP = 'keyup',
        LOAD = 'load',
        LOADABORT = 'loadabort',
        LOADCOMMIT = 'loadcommit',
        LOADEDDATA = 'loadeddata',
        LOADEDMETADATA = 'loadedmetadata',
        LOADREDIRECT = 'loadredirect',
        LOADSTART = 'loadstart',
        LOADSTOP = 'loadstop',
        LOSECAPTURE = 'losecapture',
        LOSTPOINTERCAPTURE = 'lostpointercapture',
        MESSAGE = 'message',
        MESSAGEERROR = 'messageerror',
        MOUSEDOWN = 'mousedown',
        MOUSEENTER = 'mouseenter',
        MOUSELEAVE = 'mouseleave',
        MOUSEMOVE = 'mousemove',
        MOUSEOUT = 'mouseout',
        MOUSEOVER = 'mouseover',
        MOUSEUP = 'mouseup',
        MSGESTURECHANGE = 'MSGestureChange',
        MSGESTUREEND = 'MSGestureEnd',
        MSGESTUREHOLD = 'MSGestureHold',
        MSGESTURESTART = 'MSGestureStart',
        MSGESTURETAP = 'MSGestureTap',
        MSGOTPOINTERCAPTURE = 'MSGotPointerCapture',
        MSINERTIASTART = 'MSInertiaStart',
        MSLOSTPOINTERCAPTURE = 'MSLostPointerCapture',
        MSPOINTERCANCEL = 'MSPointerCancel',
        MSPOINTERDOWN = 'MSPointerDown',
        MSPOINTERENTER = 'MSPointerEnter',
        MSPOINTERHOVER = 'MSPointerHover',
        MSPOINTERLEAVE = 'MSPointerLeave',
        MSPOINTERMOVE = 'MSPointerMove',
        MSPOINTEROUT = 'MSPointerOut',
        MSPOINTEROVER = 'MSPointerOver',
        MSPOINTERUP = 'MSPointerUp',
        OFFLINE = 'offline',
        ONLINE = 'online',
        ORIENTATIONCHANGE = 'orientationchange',
        PAGEHIDE = 'pagehide',
        PAGESHOW = 'pageshow',
        PASTE = 'paste',
        PAUSE = 'pause',
        PLAY = 'play',
        PLAYING = 'playing',
        POINTERCANCEL = 'pointercancel',
        POINTERDOWN = 'pointerdown',
        POINTERENTER = 'pointerenter',
        POINTERLEAVE = 'pointerleave',
        POINTERMOVE = 'pointermove',
        POINTEROUT = 'pointerout',
        POINTEROVER = 'pointerover',
        POINTERUP = 'pointerup',
        POPSTATE = 'popstate',
        PROPERTYCHANGE = 'propertychange',
        RATECHANGE = 'ratechange',
        READYSTATECHANGE = 'readystatechange',
        RESET = 'reset',
        RESIZE = 'resize',
        RESPONSIVE = 'responsive',
        RIGHTCLICK = 'rightclick',
        SCROLL = 'scroll',
        SEEKED = 'seeked',
        SEEKING = 'seeking',
        SELECT = 'select',
        SELECTIONCHANGE = 'selectionchange',
        SELECTSTART = 'selectstart',
        SIZECHANGED = 'sizechanged',
        SOURCECLOSED = 'sourceclosed',
        SOURCEENDED = 'sourceended',
        SOURCEOPEN = 'sourceopen',
        STALLED = 'stalled',
        STATECHANGE = 'statechange',
        STORAGE = 'storage',
        SUBMIT = 'submit',
        SUSPEND = 'suspend',
        TEXT = 'text',
        TEXTINPUT = '',
        TIMEUPDATE = 'timeupdate',
        TOUCHCANCEL = 'touchcancel',
        TOUCHEND = 'touchend',
        TOUCHMOVE = 'touchmove',
        TOUCHSTART = 'touchstart',
        TRANSITIONEND = '',
        UNLOAD = 'unload',
        UNRESPONSIVE = 'unresponsive',
        UPDATE = 'update',
        UPDATEEND = 'updateend',
        UPDATEFOUND = 'updatefound',
        UPDATESTART = 'updatestart',
        VISIBILITYCHANGE = 'visibilitychange',
        VOLUMECHANGE = 'volumechange',
        WAITING = 'waiting',
        WHEEL = 'wheel'
    }

    /**
     * Constants for pointer event names that fall back to corresponding mouse event
     * names on unsupported platforms. These are intended to be drop-in replacements
     * for corresponding values in `goog.events.EventType`.
     * @enum {string}
     */
    enum PointerFallbackEventType {
        POINTERDOWN,
        POINTERUP,
        POINTERCANCEL,
        POINTERMOVE,
        POINTEROVER,
        POINTEROUT,
        POINTERENTER,
        POINTERLEAVE
    }
}
